-- ============================================================
-- MIGRACIÓN HISTÓRICA
-- ============================================================
--
-- La protección de las funciones del dashboard se aplica
-- después de que dichas funciones sean creadas.
--
-- La configuración definitiva se encuentra en una migración
-- posterior a create_dashboard_functions.